### ISSUE TITLE
Update to CreepMiner 1.8.0

### ISSUE THREAD

**Issue by 00Asgaroth00** [ragetti/alpinepoco-creepminer#3]
Hi,

Would it be possible to update the image to use v1.8.0 of creepsky's creepMiner?

Thanks

**Comment by ragetti** [comment]
Yes, I will work on that tonight.  Sorry, I been in and out all week.

**Comment by ragetti** [comment]
I finally got it to compile, and hope to test it tonight

**Comment by ragetti** [comment]
Everything seems to be working, let me know if you have any issues.

**Comment by 00Asgaroth00** [comment]
Thank you, working great at the moment :100:
